version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_password
      POSTGRES_DB: store_admin
  backend:
    build: ./stores_backend
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      PGUSER: store_user
      PGPASSWORD: store_password
      PGDATABASE: store_admin
      PGHOST: db
      PGPORT: 5432
      PORT: 4000
    links:
      - db:db
    ports:
      - "4000:4000"
  frontend:
    build: ./stores_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
